### ISSUE TITLE
A way to detect bank based on file content?

### ISSUE THREAD

**Issue by harshmoorjani** [benjamin-awd/monopoly#143]
Right now, parser needs bank (for passwords). 
But best way to detect a bank is to look for text within the file.

Why are passwords stored per bank anyways, why can't it be a single list of passwords? That way parser can get the text without knowing the bank and can then detect the bank from file content.

Makes sense?

**Comment by harshmoorjani** [comment]
PR #144

**Comment by benjamin-awd** [comment]
@harshmoorjani 

> But best way to detect a bank is to look for text within the file.

This is a pretty good idea -- just need to be careful so that it doesn't clash with other banks I suppose.

> Why are passwords stored per bank anyways, why can't it be a single list of passwords? That way parser can get the text without knowing the bank and can then detect the bank from file content.

My initial thinking was that for each statement, we'll end up iterating over all passwords which isn't as efficient as explicitly defining passwords per bank. But honestly, this would probably only be useful in an industrial use-case where someone has hundreds of passwords and needs to parse a few thousand statements. Even then, it might only add a few seconds of runtime.

I'm happy to accept a PR for either topic. Could you split your initial PR? I'll take a look sometime this week

**Comment by harshmoorjani** [comment]
The PR, I had raised still keeps password list per bank, but creates `parser` without the `bank`.

`bank` is then passed while actually parsing...

Fot this I had to remove `@lru_cache`... couldn't figure out, how to best do it with cache enabled. May be you can help with that or let it be uncached.

**Comment by benjamin-awd** [comment]
Hey @harshmoorjani, made some changes and went ahead to merge your PR. 

Thanks again for the contribution, having a file based identifier is a pretty good idea which I'm sure will be useful for other uers in the future. 

If you have notice any issues around, feel free to comment back on this issue and I'll take a look.
